feature/footer
PaHomeAtHome/filmoteka-old pull request #1
Opened 2022-07-02 17:47 UTC by KateYankovenko

added HTML and CSS features for footer

2022-07-02 18:30 UTC, PaHomeAtHome commented on src/sass/components/_footer.scss
> +    font-size: 16px;
на мобілці та на планшеті різний розмір шрифту

2022-07-02 18:31 UTC, PaHomeAtHome commented on src/partials/footer.html
> +      &#169; 2020 | All Rights Reserved | Developed with</p>
перший закриваючий </p> (повинен бути один)

2022-07-02 18:31 UTC, PaHomeAtHome commented on src/partials/footer.html
> +    </p>
другий закриваючий </p> (повинен бути один)

2022-07-02 18:33 UTC, PaHomeAtHome requested changes
Доброго дня/вечора, отримав пул реквест, в цілому здається нормально, але потрібні невеликі виправлення.

2022-07-04 16:09 UTC, KateYankovenko commented on src/partials/footer.html
> +    </p>
+

2022-07-04 16:10 UTC, KateYankovenko commented on src/partials/footer.html
> +      &#169; 2020 | All Rights Reserved | Developed with</p>
+

2022-07-04 20:49 UTC, PaHomeAtHome approved these changes
nice work!) approved

2022-07-04 20:49 UTC, merged